// One-off data transform: reads raw extraction from _research/ and generates
// typed src/data/*.ts modules. Re-run manually whenever _research data changes.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.dirname(fileURLToPath(import.meta.url)) + '/..'
const vehiclesRaw = JSON.parse(fs.readFileSync(`${root}/_research/current-site/vehicles.json`, 'utf-8'))
const companyRaw = JSON.parse(fs.readFileSync(`${root}/_research/current-site/company.json`, 'utf-8'))

function pad2(n) {
  return String(n).padStart(2, '0')
}

// Real "Recomandat" homepage selection, extracted verbatim from abromauto.ro homepage
// (_research/text-home.txt) — not invented, matches the live site's featured order.
const FEATURED_SLUGS = [
  'byd-seal-u-dm-i',
  'renault-kadjar',
  'aigo-m1',
  'linktour-alumi-elite',
  'mercedes-c-class-c-200-d',
  'audi-a4-limuzina',
]

// Body type per vehicle — inferred from well-known, publicly documented body
// styles of these specific models (not fabricated spec/condition data), used
// only for the body-type filter facet that exists on the live site's stock page.
const BODY_TYPE = {
  'audi-a4-limuzina': 'Berlină',
  'nissan-x-trail': 'SUV',
  'renault-kadjar': 'SUV',
  'linktour-alumi-elite': 'Hatchback',
  'bmw-x1-xdrive25e': 'SUV',
  peugeot: 'SUV',
  'volvo-xc40': 'SUV',
  volvo: 'SUV',
  'aigo-m1': 'Hatchback',
  'mercedes-c-class-c-200-d': 'Berlină',
  'volkswagen-passat': 'Break',
  'bmw-seria-5-530e-xdrive': 'Berlină',
  'volkswagen-touareg': 'SUV',
  'skoda-octavia-combi-1-6-tdi-clever': 'Break',
  'peugeot-3008': 'SUV',
  'mercedes-benz-a180d': 'Hatchback',
  'mercedes-benz-a180d-2': 'Hatchback',
  'mercedes-cls-53-amg': 'Coupe',
  'nissan-qashqai': 'SUV',
  'byd-seal-u-dm-i': 'SUV',
}

// Some source pages only published a "MM.YYYY" first-registration date instead
// of a plain year (real data, not an extraction error). Normalize to a numeric
// year for sorting/filtering, keeping the original string for display.
function parseYear(rawYear) {
  if (typeof rawYear === 'number') return { year: rawYear, firstRegistration: null }
  const match = /^(\d{2})\.(\d{4})$/.exec(String(rawYear))
  if (match) return { year: Number(match[2]), firstRegistration: rawYear }
  return { year: Number(rawYear), firstRegistration: null }
}

// The live site has two ambiguous bare-brand-name slugs (/peugeot/, /volvo/)
// that don't indicate the model — per the URL audit, give them descriptive
// slugs on the new site and 301-redirect the old ones (see public/_redirects).
const SLUG_OVERRIDES = {
  peugeot: 'peugeot-2008',
  volvo: 'volvo-xc40-interior-bej',
}

function statusBadge(status) {
  if (status === 'coming-soon') return 'Disponibil în curând'
  if (status === 'sold') return 'Vândut'
  if (status === 'reserved') return 'Rezervat'
  return null
}

const vehicles = vehiclesRaw.map((v) => {
  const { year, firstRegistration } = parseYear(v.year)
  return {
  slug: SLUG_OVERRIDES[v.slug] ?? v.slug,
  legacyUrl: v.url,
  brand: v.brand,
  model: v.model,
  title: v.title,
  badge: statusBadge(v.status),
  featured: FEATURED_SLUGS.includes(v.slug),
  bodyType: BODY_TYPE[v.slug] ?? null,
  price: v.price,
  priceExcludingVAT: v.priceExcludingVAT ?? null,
  currency: v.currency,
  priceExcludesVAT: !!v.priceExcludesVAT,
  year,
  firstRegistration,
  mileage: v.mileage,
  fuel: v.fuel,
  transmission: v.transmission,
  engineCC: v.engineCC ?? null,
  powerCP: v.powerCP ?? null,
  color: v.color ?? null,
  vin: v.vin ?? null,
  status: v.status,
  description: v.description,
  equipment: v.equipment,
  imageCount: v.imageCount,
  }
})

const vehiclesTs = `// AUTO-GENERATED by scripts/build-data.mjs from _research/current-site/vehicles.json
// Real inventory data extracted from abromauto.ro. Do not hand-edit — re-run the script.
import type { Vehicle } from '@/types/vehicle'

export const vehicles: Vehicle[] = ${JSON.stringify(vehicles, null, 2)}
`

fs.writeFileSync(`${root}/src/data/vehicles.ts`, vehiclesTs)

const companyTs = `// AUTO-GENERATED by scripts/build-data.mjs from _research/current-site/company.json
// Real company/contact data extracted from abromauto.ro. Do not hand-edit — re-run the script.
import type { Company } from '@/types/company'

export const company: Company = ${JSON.stringify(companyRaw, null, 2)}
`

fs.writeFileSync(`${root}/src/data/company.ts`, companyTs)

console.log(`Wrote ${vehicles.length} vehicles -> src/data/vehicles.ts`)
console.log('Wrote company data -> src/data/company.ts')
