// AUTO-GENERATED by scripts/build-data.mjs from _research/current-site/company.json
// Real company/contact data extracted from abromauto.ro. Do not hand-edit — re-run the script.
import type { Company } from '@/types/company'

export const company: Company = {
  "brandName": "AbRom Auto",
  "legalName": "SC ABROM TRANS SRL",
  "registryNumber": "J2024000013017",
  "vatId": "CUI 49361806",
  "registeredAddress": "Str. Unirii, Nr. 3, Loc. Alba Iulia, Jud. Alba",
  "showroomAddress": "Str. Pietrar, Alba Iulia, 510158",
  "city": "Alba Iulia",
  "county": "Alba",
  "country": "România",
  "phone": "0786 087 474",
  "phoneIntl": "+40786087474",
  "telLink": "tel:0786087474",
  "email": "vanzari@abromauto.ro",
  "emailAlt": "contact@abrom-auto.ro",
  "whatsapp": {
    "number": "40786087474",
    "link": "https://wa.me/40786087474"
  },
  "hours": {
    "monFri": "08:00 - 17:00",
    "saturday": "12:30 - 15:30",
    "sunday": "12:30 - 15:30",
    "raw": {
      "Luni – Vineri": "08:00 – 17:00",
      "Sâmbătă": "12:30 – 15:30",
      "Duminică": "12:30 – 15:30"
    }
  },
  "googleMaps": {
    "placeUrl": "https://www.google.com/maps/place/ABROM+AUTO/@46.0980224,23.6126208,14z/data=!4m6!3m5!1s0x474ea926d4267cd3:0x76052c896c4fffc8!8m2!3d46.1011833!4d23.6121664!16s%2Fg%2F11n9dsx9d9",
    "lat": 46.1011833,
    "lng": 23.6121664
  },
  "social": {
    "facebook": "https://www.facebook.com/share/1JLSvT9doe/",
    "instagram": "https://www.instagram.com/abromauto",
    "tiktok": "https://www.tiktok.com/@abromauto"
  },
  "tracking": {
    "metaPixelId": "1469736181848423",
    "notes": "Meta Pixel (Facebook Pixel) confirmed present on current live site via facebook.com/tr?id=... calls on every page. No Google Analytics (GA4) or Google Tag Manager script was found on the pages fetched (home, despre-noi, finantare, contact, trade-in) — GA4/GTM likely NOT currently installed. New site should preserve the Meta Pixel ID for continuity of any running Meta Ads campaigns, and add GA4/GTM fresh since none currently exists."
  },
  "certifications": {
    "anpc": [
      "https://abromauto.ro/wp-content/uploads/2026/07/anpc-sal.png",
      "https://abromauto.ro/wp-content/uploads/2026/07/anpc-sol.png"
    ],
    "notes": "ANPC SAL/SOL badges (Romanian consumer-protection alternative dispute resolution) present in footer/legal pages — mandatory for Romanian e-commerce/consumer sites, must be preserved with links to anpc.ro / solutionarea online a litigiilor (SOL) platform."
  },
  "servicesOffered": [
    "Vânzare autovehicule rulate verificate",
    "Finanțare / credit auto pentru persoane fizice",
    "Leasing auto pentru persoane juridice",
    "Trade-In (schimb mașină veche + avans)",
    "Buy-Back (răscumpărare, condiții contractuale, pentru mașini achiziționate de la AbRom Auto)",
    "Livrare la domiciliu (pe platformă sau pe roți, prin parteneri)",
    "Apel video pentru prezentarea mașinii",
    "Rezervare auto pe bază de avans"
  ],
  "trustSignalsRealVerified": [
    "Garanție 12 luni inclusă, posibilitate extindere până la 3 ani",
    "KM certificați, garantați prin factură și istoric verificabil",
    "Raport CarVertical inclus gratuit (daune, kilometraj, utilizare anterioară)",
    "Istoric de service verificabil (acolo unde există)",
    "Verificare posibilă în service autorizat înainte de cumpărare"
  ],
  "testimonials": {
    "found": false,
    "notes": "No genuine, attributed customer testimonials were found anywhere on the crawled pages (home, despre-noi, contact, trade-in, finantare). Per instructions, do NOT fabricate testimonials on the new site. Options: omit the section entirely for now, or pull real reviews from Google Business Profile / Facebook page (would need explicit owner permission + live API/manual copy, not invented)."
  }
}
